### ISSUE TITLE
localhost:3000/api/login doesn't respond

### ISSUE THREAD

**Issue by szdavid92** [GD-SoftArch-2015/yacha#7]
```curl -X POST -d '{ "username":"dsadas", "password":"dasdasd"}' http://localhost:3000/api/login --header "Content-Type:application/json"```

Egyszeruen ennyi, nem kapok kimenetet, mintha vegtelen ciklusba kerulne a szerver.

**Comment by ggergo91** [comment]
Javítva az else ág hozzáadásával
